return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "css",
      "dart",
      "diff",
      "dockerfile",
      "go",
      "graphql",
      "html",
      "http",
      "javascript",
      "jsdoc",
      "json",
      "lua",
      "make",
      "markdown",
      "prisma",
      "python",
      "regex",
      "scala",
      "scss",
      "solidity",
      "sql",
      "svelte",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vue",
      "yaml",
    },
  },
}
